# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

```python
import numpy as np
```

In [1]:
import numpy as np

```python
#Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)
```

In [2]:
#Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


<hr>
<br>
<br>

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

```python
#Get a value at an index
arr[8]
```

In [3]:
#Get a value at an index
arr[8]

9

```python
#Get values in a range
print(arr[1:5])
```

In [4]:
#Get values in a range
print(arr[1:5])

[2 3 4 5]


```python
#Get values in a range
arr[0:5]
```

In [5]:
#Get values in a range
arr[0:5]

array([1, 2, 3, 4, 5])

In [7]:
arr[[1,2,3,4]] # indexing using a list 

array([2, 3, 4, 5])

<hr>
<br>
<br>

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

```python
print(arr)
```

In [8]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


```python
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)
```

In [9]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


```python
alist = [1,2,3,4,5,6,7]
alist[0:4] = "h"
print(alist)
```

In [10]:
alist = [1,2,3,4,5,6,7]
alist[0:4] = "h"
print(alist)

['h', 5, 6, 7]


```python
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
print(arr)
```

In [18]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


```python
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)
```

In [12]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)

[0 1 2 3 4 5]


```python
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr)
```

In [17]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr) # since the slice was made using a linkage, you change the oringinal 

[99 99 99 99 99 99]


**Now note the changes also occur in our original array!**

```python
print(arr)
```

In [16]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


**Data is not copied, it's a view of the original array! This avoids memory problems!**

```python
#To get a copy, we need to be explicit!
arr_copy = arr.copy()
print(arr_copy)
```

In [23]:
arr = np.arange(1,11)
arr_copy= arr.copy()
arr_copy[0:5] = 100
print(arr)
print(arr_copy)

[ 1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100   6   7   8   9  10]


<hr>
<br>
<br>

## Selection

Let's briefly go over how to use boolean comparisons to select certain values

```python
arr = np.arange(1,11)
print(arr)
```

In [24]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


```python
bool_arr = arr > 6
print(bool_arr)

g_than_six = arr[bool_arr]
print(g_than_six)
```

In [25]:
bool_arr = arr > 6
print(bool_arr)

g_than_six = arr[bool_arr]
print(g_than_six)

[False False False False False False  True  True  True  True]
[ 7  8  9 10]
